# Generated by Django 4.1.13 on 2025-11-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('description', models.TextField()),
                ('cover_image', models.URLField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('publication_year', models.IntegerField()),
                ('rental_price_per_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available_copies', models.IntegerField(default=1)),
                ('total_copies', models.IntegerField(default=1)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('rental_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('expected_return_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue')], max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'rentals',
            },
        ),
    ]
