# Generated by Django 4.1.13 on 2025-11-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_cartitem_order_orderitem_delete_rental_book_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='book_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
